# Generated by Django 3.1.7 on 2021-04-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcamera', '0002_auto_20210405_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
