# Generated by Django 3.1.7 on 2021-04-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcamera', '0003_auto_20210405_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
    ]
